//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _00_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public int UserID { get; set; }
        public int VehiclesID { get; set; }
        public Nullable<System.DateTime> ActualReturnDate { get; set; }
    
        public virtual UserTable UserTable { get; set; }
        public virtual VehicleInventory VehicleInventory { get; set; }
    }
}
