//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _00_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentalcarsEntities1 : DbContext
    {
        public RentalcarsEntities1()
            : base("name=RentalcarsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<CarsType> CarsTypes { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<UserTable> UserTables { get; set; }
        public virtual DbSet<VehicleInventory> VehicleInventories { get; set; }
    }
}
