//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _00_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleInventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleInventory()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int VehiclesID { get; set; }
        public int CarsTypeID { get; set; }
        public int UpdatedMileage { get; set; }
        public bool IsProperForRent { get; set; }
        public int VehicleNumber { get; set; }
        public int BranchesID { get; set; }
        public string VehiclePic { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual CarsType CarsType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
